version: '2.4'

services:
    
    backend:
    # will build ./docker/db/Dockerfile
        build: 
            ./App/server/
        ports:
            - '8000:8000'
        volumes:
            - ./App/server:/usr/src/app:delegated
            - ./App/server/package.json:/usr/src/app/package.json
            - ./App/package-lock.json:/usr/src/app/package-lock.json
            - notused:/usr/src/app/node_modules

volumes:
  notused: